frontend/package-lock.json, frontend/package.json, frontend/pages/login.tsx, frontend/postcss.config.js, frontend/styles/globals.css, frontend/tailwind.config.js
This pr aims to implement the necessary frontend and backend design for a successful login and registration process
=> login / register design

.github/workflows/ci.yml, backend/cmd/service/login/Dockerfile, backend/cmd/service/register/Dockerfile, frontend/Dockerfile
I am actually not sure if this workflow works, but it should according to [this article](https://github.com/marketplace/actions/build-and-push-docker-images)
=> Build images on push on main

.github/workflows/ci.yml, .github/workflows/frontend_service.yml, .github/workflows/login_service.yml, .github/workflows/register_service.yml
=> Fixed dockerfile path

frontend/.prettierrc, frontend/components/deck/DeckOverviewTile.stories.ts, frontend/components/deck/DeckOverviewTile.tsx, frontend/components/group/GroupAsideTile.stories.tsx, frontend/components/group/GroupAsideTile.tsx, frontend/components/group/GroupOverviewTile.stories.tsx, frontend/components/group/GroupOverviewTile.tsx, frontend/components/navigation/Navbar.stories.tsx, frontend/components/navigation/Navbar.tsx, frontend/components/navigation/Navigation.tsx, frontend/package-lock.json, frontend/package.json, frontend/pages/index.tsx, frontend/styles/Home.module.css, frontend/styles/globals.css
=> implemented index page

frontend/.storybook/preview.ts, frontend/components/deck/Deck.tsx, frontend/components/deck/DeckOverview.tsx, frontend/components/flashcard/Flashcard.tsx, frontend/components/form/FormButton.tsx, frontend/components/form/FormInput.tsx, frontend/components/input/Button.tsx, frontend/components/navigation/Header.tsx, frontend/components/statistics/Statistic.stories.ts, frontend/components/statistics/Statistic.tsx, frontend/components/statistics/StatisticOverview.stories.ts, frontend/components/statistics/StatisticOverview.tsx, frontend/pages/features.tsx, frontend/pages/home.tsx, frontend/pages/login.tsx, frontend/tailwind.config.js
This Pr implements the first statistic components
=> added first statistic components

backend/kioku-api.postman_collection.json, backend/pkg/converter/fiberSerializerTypes.go, backend/pkg/converter/typeConverter.go, backend/services/frontend/handler/frontend.go, backend/services/frontend/main.go, frontend/components/navigation/Header.tsx
This PR implements:
- logout functionality in backend & frontend
- some api request & response adjustments
=> added logout & serializer simplifications

frontend/components/flashcard/Flashcard.tsx, frontend/components/navigation/Tabs/CardsTab.tsx, frontend/components/navigation/Tabs/InvitationsTabs.tsx, frontend/pages/deck/[id]/learn.tsx
This change fixes the loading issue when learning a deck described in #67. 
@memeToasty please check whether you are satisfied with this solution.
=> Fixed card loading

frontend/components/navigation/Tabs/CardsTab.tsx, frontend/pages/deck/[id]/index.tsx
I have no clue how or why it works, but it does.
=> Fixed CardList sizing

frontend/components/navigation/Tabs/InvitationsTabs.tsx, frontend/components/navigation/Tabs/TabHeader.tsx, frontend/pages/index.tsx, frontend/types/Invitation.ts
=> Add Notification Icon for incoming Invitations

frontend/components/form/FormButton.stories.ts, frontend/components/form/FormButton.tsx, frontend/components/input/Button.stories.ts, frontend/components/input/Button.tsx, frontend/components/input/DangerAction.stories.ts, frontend/components/input/DangerAction.tsx, frontend/components/input/InputAction.stories.ts, frontend/components/input/InputAction.tsx, frontend/components/layout/Section.stories.ts, frontend/components/layout/Section.tsx, frontend/components/navigation/Tabs/DeckSettingsTab.tsx, frontend/components/navigation/Tabs/GroupSettingsTab.tsx, frontend/pages/deck/[id]/index.tsx, frontend/pages/group/[id]/index.tsx
This is how the GroupSettingsTab looks like for a non-admin user.
=> Adjust SettingsTabs according to group role

.github/workflows/release.yml
This PR adds the SRS service build job to the production workflow
=> added: SRS Service to production build job

frontend/components/group/Member.tsx
This pr reimplements the kick group member button and adjusts the corresponding endpoint
=> Reimplement kick group member button

frontend/components/layout/Header.tsx, frontend/pages/deck/[id]/index.tsx, frontend/pages/group/[id]/index.tsx, frontend/pages/index.tsx
This pr splits the `Header` component in `Header` and `FetchHeader` to resolve storybook and chromatic errors introduced by #122
=> Fix header component

frontend/components/deck/Deck.tsx, frontend/components/graphics/Logo.tsx, frontend/components/layout/Header.tsx, frontend/components/layout/Section.tsx, frontend/pages/deck/[id]/learn.tsx, frontend/pages/features.tsx, frontend/pages/login.tsx
This pr fixes the last sonarcloud issues in the frontend.
=> Fix sonarcloud issues

frontend/locales/de/messages.po, frontend/locales/en/messages.po, frontend/pages/deck/[id]/learn.tsx
Removes the broken toast message from the learning page
resolves #177
=> Fix learn card toast

frontend/components/navigation/Tabs/UserSettingsTab.tsx
This PR fixes the broken user rename functionality in the frontend.
resolves #176
=> Fix user rename

frontend/pages/login.tsx, frontend/util/reauth.ts
This pr fixes the login issue introduced in #194
=> Fix login issue

frontend/components/deck/Deck.tsx, frontend/components/input/Button.tsx, frontend/components/layout/Header.tsx, frontend/components/navigation/Navbar.tsx, frontend/components/navigation/Tabs/GroupsTab.tsx, frontend/pages/deck/[id]/learn.tsx, frontend/pages/features.tsx, frontend/pages/home.tsx, frontend/pages/login.tsx
This pr replaces routing elements using `next/link`
Resolves part of #197
=> Replace routing elements with links

frontend/pages/deck/[id]/learn.tsx, frontend/util/swr.ts
This PR aims to remove the bug where navigating to the learning page shows the congratulations item for a short period of time.
resolves #186
=> Fix early congratulation on learning page

frontend/components/deck/Deck.tsx, frontend/components/deck/DeckList.tsx, frontend/components/flashcard/CardList.tsx, frontend/components/navigation/Tabs/DecksTab.tsx, frontend/components/navigation/Tabs/TabBar.tsx, frontend/components/navigation/Tabs/TabHeader.stories.ts, frontend/components/navigation/Tabs/TabHeader.tsx, frontend/pages/_app.tsx, frontend/pages/deck/[id]/index.tsx, frontend/pages/group/[id]/index.tsx, frontend/pages/index.tsx
This pr aims to make the tabs responsive. On small windows the TabBar will be displayed at the bottom. Please don't question why or how this works. I don't know myself cause ScrollBars are weird ¯\_(ツ)_/¯. Just be happy that this works.
resolves part of #80
=> Update tabs to be responsive

frontend/package-lock.json
This pr fixes two security vulnerabilities in our frontend.
=> Fix frontend security vulnerabilities
